services:
  - type: web
    name: frameless-team05
    runtime: docker
    plan: 0.5c-512mb
    region: singapore
    branch: feature/local-backend
    healthCheckPath: /api/health
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ANALYZE_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: NAVER_CLIENT_ID
        sync: false
      - key: NAVER_CLIENT_SECRET
        sync: false
